name: Cart-service-CICD

on:
  push:
    branches:
      - main
    paths:
      - 'Cart/**'
  pull_request:
    branches:
     - main
    paths:
     - 'Cart/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker hub
        uses: docker/login-action@v1

        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Cart
            file: ./Cart/Dockerfile
            push: true
            tags: aflu/Ecome-cart-service:latest